services:
  postgres-order:
    image: postgres:18.2-alpine
    container_name: postgres-order
    environment:
      POSTGRES_USER: micromart
      POSTGRES_PASSWORD: micromart
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U micromart -d order_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres-inventory:
    image: postgres:18.2-alpine
    container_name: postgres-inventory
    environment:
      POSTGRES_USER: micromart
      POSTGRES_PASSWORD: micromart
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-inventory-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U micromart -d inventory_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8.0-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  clickhouse:
    image: clickhouse/clickhouse-server:26.2-alpine
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: micromart
      CLICKHOUSE_PASSWORD: micromart
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user", "micromart", "--password", "micromart", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  prometheus:
    image: prom/prometheus:v3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus.yaml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-order-data:
  postgres-inventory-data:
  redis-data:
  clickhouse-data:
  grafana-data:
