apiVersion: v1
kind: Secret
metadata:
  name: micromart-secrets
  namespace: micromart
type: Opaque
stringData:
  ORDER_DATABASE_URL: "postgres://micromart:micromart@postgres-order:5432/order_db?sslmode=disable"
  INVENTORY_DATABASE_URL: "postgres://micromart:micromart@postgres-inventory:5432/inventory_db?sslmode=disable"
  CLICKHOUSE_USER: "micromart"
  CLICKHOUSE_PASSWORD: "micromart"
